"""Subset the wordmark typeface and embed it in CSS.

    python tools/build_font.py

Writes docs/css/wordmark.css, containing an @font-face whose src is a base64
WOFF2 of Pinyon Script cut down to the handful of characters the wordmark needs.

Why embedded rather than a font file next to the CSS: the game has to run by
double-clicking index.html, and browsers treat a font fetched from a file://
page as cross-origin and refuse it. A data URI inside the stylesheet loads
regardless, and keeps the game working offline with no extra request.

Needs fontTools and brotli, which are build-time only:

    python -m pip install fonttools brotli

Pinyon Script is under the SIL Open Font License 1.1, which permits subsetting
and redistribution; the license travels with it in fonts/OFL-PinyonScript.txt.
"""

import base64
import io
import os
import sys
import urllib.request

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP = os.path.join(ROOT, "docs")        # the shipped game; see build_corpus.py
CACHE = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".cache", "fonts")

FAMILY = "Pinyon Script"
SLUG = "pinyonscript"
FILE = "PinyonScript-Regular.ttf"
RAW = "https://raw.githubusercontent.com/google/fonts/main/ofl/%s/%s"

# The wordmark, plus enough of the alphabet to set a short heading in the same
# hand later without rebuilding. A script face at this size is a few KB either
# way, so the flexibility is nearly free.
CHARS = ("Historic Ink"
         "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
         "abcdefghijklmnopqrstuvwxyz"
         " '’&,.-—")


def fetch(name):
    os.makedirs(CACHE, exist_ok=True)
    path = os.path.join(CACHE, name)
    if not os.path.exists(path):
        url = RAW % (SLUG, name)
        req = urllib.request.Request(url, headers={"User-Agent": "wordmark-build/1.0"})
        with urllib.request.urlopen(req, timeout=90) as r:
            data = r.read()
        with open(path, "wb") as f:
            f.write(data)
        print("downloaded %s (%.1f KB)" % (name, len(data) / 1024))
    return path


def main():
    try:
        from fontTools import subset
        from fontTools.ttLib import TTFont
    except ImportError:
        print("needs fontTools: python -m pip install fonttools brotli")
        return 1

    src = fetch(FILE)
    license_path = fetch("OFL.txt")

    font = TTFont(src)
    options = subset.Options()
    # Keep the layout features: a script face leans on kerning and contextual
    # alternates to make its letters join, and stripping them breaks the joins.
    options.layout_features = ["*"]
    options.desubroutinize = True
    options.drop_tables += ["DSIG"]
    options.notdef_outline = False
    options.recalc_bounds = True

    subsetter = subset.Subsetter(options=options)
    subsetter.populate(text=CHARS)
    subsetter.subset(font)

    font.flavor = "woff2"
    buf = io.BytesIO()
    font.save(buf)
    woff2 = buf.getvalue()

    original = os.path.getsize(src)
    b64 = base64.b64encode(woff2).decode("ascii")

    out = os.path.join(APP, "css", "wordmark.css")
    with open(out, "w", encoding="utf-8") as f:
        f.write(
            "/* GENERATED by tools/build_font.py -- do not edit.\n"
            " *\n"
            " * %s, subset to the characters the wordmark uses and embedded so the\n"
            " * game still works opened straight from the filesystem, where a linked\n"
            " * font file counts as cross-origin and is refused.\n"
            " *\n"
            " * SIL Open Font License 1.1 -- see fonts/OFL-PinyonScript.txt\n"
            " */\n"
            "@font-face {\n"
            "  font-family: 'Pinyon Script';\n"
            "  font-style: normal;\n"
            "  font-weight: 400;\n"
            "  font-display: swap;\n"
            "  src: url(data:font/woff2;base64,%s) format('woff2');\n"
            "}\n" % (FAMILY, b64))

    fonts_dir = os.path.join(APP, "fonts")
    os.makedirs(fonts_dir, exist_ok=True)
    with open(license_path, "r", encoding="utf-8") as f:
        text = f.read()
    with open(os.path.join(fonts_dir, "OFL-PinyonScript.txt"), "w", encoding="utf-8") as f:
        f.write(text)

    print("%s: %.1f KB original -> %.1f KB subset woff2 -> %.1f KB of CSS"
          % (FAMILY, original / 1024, len(woff2) / 1024,
             os.path.getsize(out) / 1024))
    print("wrote docs/css/wordmark.css and docs/fonts/OFL-PinyonScript.txt")
    return 0


if __name__ == "__main__":
    sys.exit(main())
